apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
generators:
  - ../../base/helm-chart.yaml
patches:
- target:
    kind: CustomResourceDefinition
  path: ../../../../../patches/patch-crds.yaml
