---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-listener
spec:
  hostBinding:
    namespace:
      from: ALL
  port: 80
  protocol: HTTP
  securityModel: XFP
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: https-listener
spec:
  hostBinding:
    namespace:
      from: ALL
  port: 443
  protocol: HTTPS
  securityModel: XFP
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: argocd
spec:
  hostname: edge.infra.lan
  requestPolicy:
    insecure:
      action: Route
# ---
# apiVersion: getambassador.io/v2
# kind: Mapping
# metadata:
#   name: argocd-server-ui
# spec:
#   host: edge.infra.lan
#   prefix: /argo-cd
#   rewrite: /argo-cd
#   service: http://argocd-server.argocd:80      
