apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- ../../base/helm-chart.yaml
patches:
- target:
    kind: CustomResourceDefinition
  path: ../../../../../patches/patch-crds.yaml