apiVersion: builtin
kind: HelmChartInflationGenerator
name: &name metallb
metadata:
  name: *name
version: 0.14.9
repo: https://metallb.github.io/metallb
releaseName: *name
namespace: metallb-system
includeCRDs: &crd true
AdditionalValuesFiles:
- ../../base/values.yaml
- values.yaml
apiVersions:
- policy/v1



# index 5898a5e8..00000000
# @@ -1,20 +0,0 @@
# -# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_
# -# https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/helmchartargs.go
# -# artifacthub                                       https://artifacthub.io/packages/helm/metallb/metallb
# -# values.yaml                                       https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml
# -apiVersion: builtin
# -kind: HelmChartInflationGenerator # helmCharts
# -metadata:
# -  name: metallb-helm-chart
# -name: &name metallb                     # Name is the name of the chart, e.g. 'minecraft'.
# -# Starting from v0.13.0 configInline is no longer supported. Please see https://metallb.universe.tf/#backward-compatibility
# -version: 0.14.8                         # Version is the version of the chart, e.g. '3.1.3'
# -repo: https://metallb.github.io/metallb # Repo is a URL locating the chart on the internet.
# -releaseName: *name                      # ReleaseName replaces RELEASE-NAME in chart template output,
# -namespace: metallb-system               # Namespace set the target namespace for a release.
# -includeCRDs: &crd true                      # IncludeCRDs specifies if Helm should also generate CustomResourceDefinitions. Defaults to 'false'.
# -valuesFile: values-metallb.yaml         # ValuesFile is local file path to a values file to use _instead of_ the default values that accompanied the chart. The default values are in '{ChartHome}/{Name}/values.yaml'.
# -valuesInline:                           # ValuesInline holds value mappings specified directly, rather than in a separate file.
# -  crds:
# -    enabled: *crd
# -valuesMerge: merge