apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../base
generators:
- ../../base/helm-chart.yaml
patches:
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-options: Replace=true,ServerSideApply=true
  target:
    kind: CustomResourceDefinition
- patch: |-
    - op: replace
      path: /spec/template/metadata/labels/app.kubernetes.io~1part-of
      value: argocd-redis-secret-init
  target:
    kind: Job
    name: argocd-redis-secret-init