global:
  domain: argocd.apps.io
  logging:
    # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
    level: debug
server:
  ingress:
    enabled: true
    tls: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
configs:
  secret:
    argocdServerAdminPassword: "$2a$10$6ZsSd4LcJiyJCwAa/G1Yg.MSyJTKHire1ubRZoWSfZex0n4bNneZi"