global:
  domain: argocd.apps.io
  logging:
    # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
    level: debug
server:
  ingress:
    enabled: true
    tls: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
configs:
  secret:
    argocdServerAdminPassword: "$2a$10$6ZsSd4LcJiyJCwAa/G1Yg.MSyJTKHire1ubRZoWSfZex0n4bNneZi"
  params:
    ## Server properties
    # -- Run server without TLS
    ## NOTE: This value should be set when you generate params by other means as it changes ports used by ingress template.
    server.insecure: true
    # -- Value for base href in index.html. Used if Argo CD is running behind reverse proxy under subpath different from /
    server.basehref: /argo-cd
    # -- Used if Argo CD is running behind reverse proxy under subpath different from /
    server.rootpath: /argo-cd
