apiVersion: builtin
kind: HelmChartInflationGenerator
name: &name crossplane
metadata:
  name: *name
version: 1.19.2
repo: https://charts.crossplane.io/stable
releaseName: *name
namespace: crossplane-system
includeCRDs: &crd true