apiVersion: organizations.aws.upbound.io/v1beta1
kind: Account
metadata:
  name: demo
  annotations:
    # crossplane.io/external-name: ""
    argocd.argoproj.io/tracking-id: crossplane-system-infrastructure:/Account:crossplane-system/demo
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  forProvider:
    region: eu-west-3
    email: "aws-demo-176432.compacted698@passinbox.com"
    name: demo-176432
    closeOnDeletion: true
  providerConfigRef:
    name: default
# ---
# apiVersion: aws.upbound.io/v1beta1
# kind: ProviderConfig
# metadata:
#   name: demo
#   annotations:
#     argocd.argoproj.io/tracking-id: crossplane-system-infrastructure:/ProviderConfig:crossplane-system/demo
#     argocd.argoproj.io/compare-options: IgnoreExtraneous
#     argocd.argoproj.io/sync-options: Prune=false
# spec:
#   # same as default's ProviderConfig
#   credentials:
#     source: Secret
#     secretRef:
#       namespace: crossplane-system
#       name: aws-org-admin
#       key: creds
#   assumeRoleChain:
#   - roleARN: arn:aws:iam::1234567890:role/OrganizationAccountAccessRole
# ---
# apiVersion: iam.aws.upbound.io/v1beta1
# kind: Role
# metadata:
#   name: controlplane
#   annotations:
#     # crossplane.io/external-name: "controlplane"
#     argocd.argoproj.io/tracking-id: crossplane-system-infrastructure:/Role:crossplane-system/controlplane
#     argocd.argoproj.io/compare-options: IgnoreExtraneous
#     argocd.argoproj.io/sync-options: Prune=false
# spec:
#   # deletionPolicy: Delete
#   forProvider:
#     assumeRolePolicy: |
#       {
#         "Version": "2012-10-17",
#         "Statement": [{
#           "Effect": "Allow",
#           "Principal": {"Service": ["eks.amazonaws.com"]},
#           "Action": ["sts:AssumeRole"]
#         }]
#       }
#   # initProvider: {}
#   # managementPolicies:
#   #   - '*'
#   providerConfigRef:
#     name: demo
