apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
- root/organization.yaml
- account.yaml
- ../../base/crossplane-kubernetes/package/definition.yaml
- ../../base/crossplane-kubernetes/package/compositions.yaml