apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
- root/organization.yaml
- account.yaml
- ../../base/crossplane-kubernetes/package/definition.yaml
- ../../base/crossplane-kubernetes/package/compositions.yaml
# - ../../base/crossplane-kubernetes/providers/function-kcl.yaml
- ../../base/crossplane-kubernetes/providers/provider-helm-incluster.yaml
patches:
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.crossplane.io/v1
      kind: Composition
      metadata:
        name: cluster-azure
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.crossplane.io/v1
      kind: Composition
      metadata:
        name: cluster-google
  - target:
      kind: ServiceAccount
      name: crossplane-provider-helm
    patch: |-
      - op: replace
        path: /metadata/annotations/crossplane-system-infrastructure
        value: pkg.crossplane.io/ControllerConfig:crossplane-system/crossplane-provider-helm