apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    kind: CustomResourceDefinition
  path: ../../../../../patches/patch-crds.yaml
- target:
    kind: CustomResourceDefinition
  patch: |-
    - op: remove
      path: /spec/preserveUnknownFields