apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# generators:
# - ../../base/helm-chart-kyverno-policies.yaml
resources:
- ../../base
patches:
- target:
    kind: CustomResourceDefinition
  path: ../../../../../patches/patch-crds.yaml