apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
# resources:
# - aws/upbound/account.yaml
# - aws/upbound/ec2.yaml
# - aws/upbound/eks.yaml
# - aws/upbound/iam.yaml
# - aws/upbound/organizations.yaml
# - helm.yaml
# - kubernetes.yaml
# patches:
# - target:
#     kind: Provider
#     group: pkg.crossplane.io
#     version: v1
#   path: ../../../../patches/patch-providers.yaml