apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edge-stack-apiext
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edge-stack-apiext
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edge-stack-apiext
subjects:
  - kind: ServiceAccount
    name: edge-stack
    namespace: ambassador
