apiVersion: organizations.aws.upbound.io/v1beta1
kind: Account
metadata:
  name: demo
  annotations:
    crossplane.io/external-name: '322872274774'
    argocd.argoproj.io/tracking-id: crossplane-system-infrastructure:/Account:crossplane-system/demo
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  forProvider:
    region: eu-west-3
    email: "aws-demo-176432.compacted698@passinbox.com"
    name: demo-176432
    closeOnDeletion: true
    parentId: r-501c
  providerConfigRef:
    name: default
