controller:
  admissionWebhooks:
    enabled: false
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.40.255.205
  extraArgs:
    default-ssl-certificate: ingress-nginx/default-cert